file_format: "1"
id: cygnus
name: Cygnus
type: shield
url: https://github.com/adwaymalhotra/zmk
requires: [pro_micro]
features:
  - keys
siblings:
  - cygnus_central_dongle
  - cygnus_central_left
  - cygnus_peripheral_left
  - cygnus_peripheral_right
