# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_TIMEOUT=30000
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

CONFIG_ZMK_COMBO_MAX_PRESSED_COMBOS=15
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=15
#
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=8
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=8

# Enable USB since rp2040_zero is a base Zephyr board and does not enable it by default
CONFIG_ZMK_USB=y

# Enable retention boot mode for rp2040 so &sys_reset and &bootloader work correctly
CONFIG_RETAINED_MEM=y
CONFIG_RETENTION=y
CONFIG_RETENTION_BOOT_MODE=y
